### ISSUE TITLE
NC 24.0.5 Erstellung der eID-Verknüpfung fehlgeschlagen

### ISSUE THREAD

**Issue by dr-br** [eid-login/eid-login-nextcloud#11]
Hallo,
ich betreibe innerhalb eines Docker-Containers einen `Nextcloud 24.0.5` Server. Dieser wird über einen (nicht containerisierten) Apache Proxy exponiert. Der relevante Part in der apache-config Datei (vgl. #7) dürfte sein

```
RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-Port "443"

ProxyPass / http://localhost:8080/
ProxyPassReverse / http://localhost:8080/
```

Im docker-compose.yml steht das hier:
```
  app:
    image: nextcloud:latest
    restart: always
    ports:
      - 8080:80
    ....
```

Installiert ist `eidlogin: 1.0.9`.

Beim Verknüpfen der eID Karte kommt folgende Fehlermeldung:

`Erstellung der eID-Verknüpfung fehlgeschlagen! Bitte stellen Sie sicher, dass die genutzte eID-Karte gültig ist.`

Was mache ich falsch? Welche Logs helfen mir/euch weiter? 

Dank und Gruß
